/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package a3_maq_vendas_final.telas;

import a3_maq_vendas_final.banco.Banco;
import javax.swing.JOptionPane;

/**
 *
 * @author gatra
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        pass_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 275));
        setPreferredSize(new java.awt.Dimension(425, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Insira suas credenciais para proseguir:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 227, 16);

        jLabel2.setText("Usuário:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 240, 16);

        user_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(user_field);
        user_field.setBounds(6, 62, 388, 22);

        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 180, 16);

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button);
        login_button.setBounds(140, 180, 107, 47);
        getContentPane().add(pass_field);
        pass_field.setBounds(10, 140, 380, 22);

        setSize(new java.awt.Dimension(416, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        Banco check = new Banco();
        String pass = pass_field.getText();
        String user = user_field.getText();
        
        if(check.ValidarSenha(user, pass)==true){
             painel_admin adm = new painel_admin();
             adm.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Credenciais Invalidas.");
        }
       
    }//GEN-LAST:event_login_buttonActionPerformed

    private void user_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JTextField user_field;
    // End of variables declaration//GEN-END:variables
}
