/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3_maq_vendas_final.telas;

import a3_maq_vendas_final.banco.Banco;
import a3_maq_vendas_final.classes.Produto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gatra
 */
public class painel_admin extends javax.swing.JFrame {

    /**
     * Creates new form painel_admin
     */
    public painel_admin() {
        initComponents();
        Popular_overview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coluna_id = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        coluna_nome = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        coluna_estoque = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        coluna_vendida = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        coluna_compra = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        coluna_pvenda = new javax.swing.JTextArea();
        Atualizar = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        name_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qty_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bprice_field = new javax.swing.JTextField();
        sprice_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Cadastrar_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        busca_alt_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nome_alt_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        qtd_alt_field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pcompra_alt_field = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pvenda_alt_field = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        alt_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search_alt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 70, 30, 16);

        coluna_id.setColumns(20);
        coluna_id.setRows(5);
        jScrollPane2.setViewportView(coluna_id);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 90, 36, 300);

        jLabel2.setText("Nome do Produto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 70, 150, 16);

        coluna_nome.setColumns(20);
        coluna_nome.setRows(5);
        jScrollPane3.setViewportView(coluna_nome);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(240, 90, 150, 300);

        jLabel3.setText("Qtd. Estoque");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 70, 90, 16);

        coluna_estoque.setColumns(20);
        coluna_estoque.setRows(5);
        jScrollPane4.setViewportView(coluna_estoque);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(400, 90, 90, 300);

        coluna_vendida.setColumns(20);
        coluna_vendida.setRows(5);
        jScrollPane5.setViewportView(coluna_vendida);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(510, 90, 80, 300);

        jLabel4.setText("Qtd. Vendida");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 70, 90, 20);

        jLabel5.setText("Preco Compra");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(610, 70, 110, 16);

        coluna_compra.setColumns(20);
        coluna_compra.setRows(5);
        jScrollPane6.setViewportView(coluna_compra);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(610, 90, 90, 300);

        jLabel6.setText("Preco Venda");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(720, 70, 100, 16);

        coluna_pvenda.setColumns(20);
        coluna_pvenda.setRows(5);
        jScrollPane7.setViewportView(coluna_pvenda);

        jPanel1.add(jScrollPane7);
        jScrollPane7.setBounds(720, 90, 90, 300);

        Atualizar.setText("Buscar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Atualizar);
        Atualizar.setBounds(10, 120, 170, 30);

        search_field.setText("Digite um ID para procurar");
        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(search_field);
        search_field.setBounds(10, 92, 170, 20);

        jTabbedPane1.addTab("Overview", jPanel1);

        jLabel7.setText("Nome do Produto");

        jLabel8.setText("Quantidade em Estoque");

        jLabel9.setText("Preco de Compra");

        jLabel10.setText("Preco de Venda");

        Cadastrar_button.setText("Cadastrar Produto");
        Cadastrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qty_field)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bprice_field, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(sprice_field, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(Cadastrar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bprice_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprice_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Cadastrar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Incluir novos itens", jPanel2);

        busca_alt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_alt_fieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Digite o ID do produto a ser alterado");

        jLabel12.setText("Nome do Produto");

        qtd_alt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtd_alt_fieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Quantidade em Estoque");

        pcompra_alt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcompra_alt_fieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Preco de Compra");

        jLabel15.setText("Preco de Venda");

        alt_button.setText("ALTERAR");
        alt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_buttonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 145, 145));
        jButton2.setText("DELETAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        search_alt.setText("jButton1");
        search_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_altActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(busca_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nome_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(alt_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtd_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcompra_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pvenda_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busca_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtd_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcompra_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pvenda_alt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_alt))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar Cadastro", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(1050, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        if (search_field.getText().equals("Digite um ID para procurar")|search_field.getText().equals("")){
          Popular_overview();
        }
        else{
            Banco search = new Banco();
            try {
                Produto prod = search.Read(Integer.parseInt(search_field.getText()));
                coluna_id.setText(""+prod.getId());
                coluna_nome.setText(""+prod.getNome());
                coluna_estoque.setText(""+prod.getQuantidade_disponivel());
                coluna_vendida.setText(""+prod.getQuantidade_vendida());
                coluna_compra.setText(""+prod.getPreco_compra());
                coluna_pvenda.setText(""+prod.getPreco_venda());
            } catch (SQLException ex) {
                Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_AtualizarActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void Cadastrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_buttonActionPerformed
        String nome = name_field.getText();
        int qtd = Integer.parseInt(qty_field.getText());
        Double pcompra = Double.parseDouble(bprice_field.getText());
        Double pvenda = Double.parseDouble(sprice_field.getText());
        Banco ins = new Banco();
            
        try {
            ins.Insert(nome, qtd, pcompra, pvenda);
            JOptionPane.showMessageDialog(null,"Item Inserido com Sucesso!");
            name_field.setText("");
            qty_field.setText("");
            bprice_field.setText("");
            sprice_field.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Cadastrar_buttonActionPerformed

    private void qtd_alt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtd_alt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtd_alt_fieldActionPerformed

    private void pcompra_alt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcompra_alt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcompra_alt_fieldActionPerformed

    private void alt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_buttonActionPerformed
        String nome = nome_alt_field.getText();
        int qtd = Integer.parseInt(qtd_alt_field.getText());
        Double pcompra = Double.parseDouble(pcompra_alt_field.getText());
        Double pvenda = Double.parseDouble(pvenda_alt_field.getText());
        int id = Integer.parseInt(busca_alt_field.getText());
        Banco alt = new Banco();
        try {
            alt.Update(nome, qtd, pcompra, pvenda, id);
            JOptionPane.showMessageDialog(null,"Item Alterado com Sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_alt_buttonActionPerformed

    private void busca_alt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_alt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busca_alt_fieldActionPerformed

    private void search_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_altActionPerformed
        Banco found = new Banco();
        try {
            Produto alvo = found.Read(Integer.parseInt(busca_alt_field.getText()));
            nome_alt_field.setText(alvo.getNome());
            qtd_alt_field.setText(""+alvo.getQuantidade_disponivel());
            pcompra_alt_field.setText(""+alvo.getPreco_compra());
            pvenda_alt_field.setText(""+alvo.getPreco_venda());
            
        } catch (SQLException ex) {
            Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_altActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt(busca_alt_field.getText());
        Banco del = new Banco();
        try {
            del.Delete(id);
            JOptionPane.showMessageDialog(null,"Item Deletado com Sucesso!");
            nome_alt_field.setText("");
            qtd_alt_field.setText("");
            pcompra_alt_field.setText("");
            pvenda_alt_field.setText("");
            busca_alt_field.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void Popular_overview(){
        Banco pop = new Banco();
        try {
            String [][] content = pop.Read_all();
            String ids = "";
            String nomes = "";
            String qtd_vendas = "";
            String qtd_estoques = "";
            String p_compras = "";
            String p_vendas = "";
            for (int i=0;i<content.length;i++){
                ids = ids + content[i][0]+"\n";
                nomes = nomes + content[i][1]+"\n";
                qtd_estoques = qtd_estoques + content[i][2]+"\n";
                qtd_vendas = qtd_vendas + content[i][3]+"\n";
                p_compras = p_compras + content[i][4]+"\n";
                p_vendas = p_vendas + content[i][5]+"\n";
            }
            coluna_id.setText(ids);
            coluna_nome.setText(nomes);
            coluna_estoque.setText(qtd_estoques);
            coluna_vendida.setText(qtd_vendas);
            coluna_compra.setText(p_compras);
            coluna_pvenda.setText(p_vendas);
        } catch (SQLException ex) {
            Logger.getLogger(painel_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Cadastrar_button;
    private javax.swing.JButton alt_button;
    private javax.swing.JTextField bprice_field;
    private javax.swing.JTextField busca_alt_field;
    private javax.swing.JTextArea coluna_compra;
    private javax.swing.JTextArea coluna_estoque;
    private javax.swing.JTextArea coluna_id;
    private javax.swing.JTextArea coluna_nome;
    private javax.swing.JTextArea coluna_pvenda;
    private javax.swing.JTextArea coluna_vendida;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField nome_alt_field;
    private javax.swing.JTextField pcompra_alt_field;
    private javax.swing.JTextField pvenda_alt_field;
    private javax.swing.JTextField qtd_alt_field;
    private javax.swing.JTextField qty_field;
    private javax.swing.JButton search_alt;
    private javax.swing.JTextField search_field;
    private javax.swing.JTextField sprice_field;
    // End of variables declaration//GEN-END:variables
}
